import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import { toPng } from 'html-to-image'

type Props = {
  expenses: any[]
  summary: any
  analytics: any

  month: string
  year: string

  generatedBy: string

  roomName?: string
}

export async function exportProfessionalReport({
  expenses,
  summary,
  analytics,

  month,
  year,

  generatedBy,

  roomName = 'Rab Residency 201',
}: Props) {
  const doc = new jsPDF()

  const pageWidth = doc.internal.pageSize.getWidth()

  const currentDate = new Date()

  /* =================================================
     HEADER
  ================================================= */

  doc.setFontSize(22)

  doc.setTextColor(30, 30, 30)

  doc.text('ROOM EXPENSE REPORT', pageWidth / 2, 20, {
    align: 'center',
  })

  doc.setFontSize(11)

  doc.text(`Room Name: ${roomName}`, 14, 35)

  doc.text(`Month: ${month}/${year}`, 14, 42)

  doc.text(`Generated By: ${generatedBy}`, 14, 49)

  doc.text(`Generated At: ${currentDate.toLocaleString()}`, 14, 56)

  /* =================================================
     SUMMARY SECTION
  ================================================= */

  doc.setFillColor(240, 240, 240)

  doc.rect(14, 65, 182, 12, 'F')

  doc.setFontSize(14)

  doc.text('SUMMARY', 16, 73)

  doc.setFontSize(11)

  let y = 86

  const summaryRows = [
    ['Total Expense', `${summary.total.toFixed(2)}`],

    ['Per Head Expense', `${summary.perHead.toFixed(2)}`],

    ['Top Spender', analytics.topSpender.name],

    ['Most Active User', analytics.mostActiveUser.name],

    ['Total Entries', analytics.totalEntries.toString()],
  ]

  summaryRows.forEach((row) => {
    doc.text(`${row[0]}:`, 16, y)

    doc.text(row[1], 90, y)

    y += 8
  })

  /* =================================================
     SETTLEMENTS
  ================================================= */

  y += 8

  doc.setFillColor(240, 240, 240)

  doc.rect(14, y - 5, 182, 12, 'F')

  doc.setFontSize(14)

  doc.text('SETTLEMENTS', 16, y + 3)

  y += 18

  if (summary.settlements.length === 0) {
    doc.text('No settlements required', 16, y)

    y += 10
  } else {
    summary.settlements.forEach((s: any, index: number) => {
      // 🔥 Smaller font
      doc.setFontSize(9)

      const settlementText = `${index + 1}. ${s.from.name} pays ${
        s.to.name
      } ${s.amount.toFixed(2)}`

      // ✅ Auto-wrap inside width
      const splitText = doc.splitTextToSize(
        settlementText,
        170, // max width
      )

      // ✅ Render wrapped text
      doc.text(splitText, 16, y)

      // ✅ Dynamic spacing
      y += splitText.length * 5 + 2

      // ✅ Page break protection
      if (y > 260) {
        doc.addPage()

        y = 20
      }
    })
  }

  /* =================================================
     EXPENSE TABLE
  ================================================= */

  autoTable(doc, {
    startY: y + 10,

    head: [['Title', 'Category', 'Amount', 'Paid By', 'Date']],

    body: expenses.map((e) => [
      e.title,

      e.category || 'General',

      `${e.amount}`,

      e.paidBy?.name || '-',

      new Date(e.date).toLocaleDateString(),
    ]),

    styles: {
      fontSize: 10,
    },

    headStyles: {
      fillColor: [30, 41, 59],
    },
  })

  /* =================================================
     CHARTS
  ================================================= */

  let chartY = (doc as any).lastAutoTable.finalY + 20

  const chartElements = [
    {
      id: 'category-chart',
      title: 'Category Analytics',
    },

    {
      id: 'user-chart',
      title: 'User Contributions',
    },

    {
      id: 'trend-chart',
      title: 'Expense Trends',
    },
  ]

 for (const chart of chartElements) {
   const element = document.getElementById(chart.id)

   if (!element) continue

   if (chartY > 220) {
     doc.addPage()

     chartY = 20
   }

   doc.setFontSize(14)

   doc.text(chart.title, 14, chartY)

   chartY += 10

   // ✅ MODERN CSS SAFE
   const image = await toPng(element, {
     cacheBust: true,

     backgroundColor: '#ffffff',
   })

   doc.addImage(image, 'PNG', 14, chartY, 180, 80)

   chartY += 95
 }

  /* =================================================
     FOOTER
  ================================================= */

  const pageCount = (doc as any).internal.pages.length - 1

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)

    doc.setFontSize(10)

    doc.text(`Generated by ${roomName}`, 14, 290)

    doc.text(`Page ${i} of ${pageCount}`, 170, 290)
  }

  /* =================================================
     SAVE
  ================================================= */

  doc.save(`room-report-${month}-${year}.pdf`)
}
